name: CI/CD for Docker Models

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Temporary Image
        run: |
          docker build -t ekrata/echomimic_v2:build .
          docker push ekrata/echomimic_v2:build

      # - name: Test Docker Image
      #   run: docker run echomimic_v2:build npm test

  push_to_staging:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull and Tag Staging Image
        run: |
          docker pull ekrata/echomimic_v2:build
          docker tag ekrata/echomimic_v2:build ekrata/echomimic_v2:staging
          docker push ekrata/echomimic_v2:staging

  publish_to_production:
    needs: push_to_staging
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull and Re-tag for Production
        run: |
          docker pull ekrata/echomimic_v2:staging
          docker tag ekrata/echomimic_v2:staging ekrata/echomimic_v2:latest
          docker push ekrata/echomimic_v2:latest
