name: CI/CD for Docker Models

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # when set to "true" but frees about 6 GB
          tool-cache: true

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Build and Push Temporary Image
        run: |
          docker build -t ekrata/echomimic_v2:build .
          docker push ekrata/echomimic_v2:build

      # - name: Test Docker Image
      #   run: docker run echomimic_v2:build npm test

      - name: Pull and Tag Staging Image
        run: |
          docker tag ekrata/echomimic_v2:build ekrata/echomimic_v2:staging
          docker push ekrata/echomimic_v2:staging

      - name: Pull and Re-tag for Production
        run: |
          docker tag ekrata/echomimic_v2:staging ekrata/echomimic_v2:latest
          docker push ekrata/echomimic_v2:latest
